build:
  stage: build
  before_script:
    - mkdir -p .artifacts
  script:
    - cargo test --release
    # macOS for Apple Silicon (M1)
    - cargo build --release --target=aarch64-apple-darwin
    # Copy static files to executable folder
    - cp -R static target/aarch64-apple-darwin/release/
    # Create archive for macOS
    - tar -zcvf .artifacts/ArenaOfIdeas-macos.tar.gz -C target/aarch64-apple-darwin/release .
  artifacts:
    paths:
      - .artifacts
    expire_in: 7 days
