[workspace]
members = ["server"]

[workspace.package]
version = "1.0.3"
edition = "2021"

[package]
name = "arena-of-ideas"
version.workspace = true
edition.workspace = true


[workspace.dependencies]
spacetimedb = { version = "0.11.0" }

[dependencies]
spacetimedb-sdk = "0.11.0"
spacetimedb-sats = "0.11.0"
spacetimedb-lib = "0.11.0"
bevy = { version = "0.14.1", default-features = false, features = [
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_winit",
    "multi_threaded",
    "file_watcher",
    "bevy_ui",
    "bevy_text",
    "default_font",
    "x11",
] }
bevy_asset_loader = { version = "0.21.0", features = [
    "standard_dynamic_assets",
] }
bevy_common_assets = { version = "0.11.0", features = ["ron"] }
bevy_egui = { version = "0.29.0", features = ["serde"] }
egui_extras = { version = "0.28.1", features = ["svg"] }
ecolor = { version = "0.28.1", features = ["color-hex"] }
log = "0.4.19"
serde = "1"
serde_json = "1.0.104"
ron = "0.8.0"
itertools = "0.12.1"
anyhow = "1.0.75"
strum = "0.26.2"
strum_macros = "0.26.2"
tween = "2.0.1"
rand = "0.8.5"
color-hex = "0.2.0"
rand_chacha = "0.3.1"
colored = "2.0.0"
clap = { version = "4.4.5", features = ["derive"] }
hex = "0.4.3"
ordered_hash_map = "0.4.0"
home = "0.5.5"
lazy_static = "1.4.0"
convert_case = "0.6.0"
indexmap = { version = "2.2.5", features = ["serde"] }
noisy_bevy = "0.7.0"
chrono = "0.4.38"
egui_commonmark = "0.17.0"
bevy_tasks = "0.14.1"
regex = "1.10.5"
once_cell = "1.19.0"
bevy_dylib = "0.14.1"

[dependencies.winit]
version = "0.30.5"
features = ["default"]

[profile.dev.package."*"]
opt-level = 3
codegen-units = 1

[profile.release]
debug = true
