[workspace]
members = ["server"]

[workspace.package]
version = "0.6.0"
edition = "2021"

[package]
name = "arena-of-ideas"
version.workspace = true
edition.workspace = true


[workspace.dependencies]
spacetimedb = { version = "0.8.1", features = ["getrandom"] }

[dependencies]
spacetimedb-sdk = "0.8.1"
bevy = { version = "0.11.0", default-features = false, features = [
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_winit",
    "multi-threaded",
    "filesystem_watcher",
    "bevy_ui",
    "bevy_text",
    "default_font",
    "x11",
] }
ecolor = { version = "0.23.0", features = ["color-hex"] }
bevy_asset_loader = { version = "0.17.0", features = [
    "standard_dynamic_assets",
] }
bevy_common_assets = { version = "0.7.0", features = ["ron"] }
bevy_mod_picking = { version = "0.15.0", default-features = false, features = [
    "backend_raycast",
    "backend_bevy_ui",
    "selection",
] }
bevy_egui = { version = "0.22", features = ["serde"] }
log = "0.4.19"
serde = "1"
serde_json = "1.0.104"
ron = "0.8.0"
itertools = "0.11.0"
anyhow = "1.0.75"
strum_macros = "0.25.2"
tween = "2.0.1"
rand = "0.8.5"
color-hex = "0.2.0"
rand_chacha = "0.3.1"
colored = "2.0.0"
bevy_pkv = "0.8.0"
clap = { version = "4.4.5", features = ["derive"] }
bevy_kira_audio = { version = "0.17.0", features = ["settings_loader"] }
strum = "0.25.0"
hex = "0.4.3"
kira = "0.8.5"
ordered_hash_map = "0.4.0"
home = "0.5.5"
lazy_static = "1.4.0"
convert_case = "0.6.0"

[dependencies.winit]
# version = "*"
version = "0.29.4"
features = ["default"]

[profile.dev.package."*"]
opt-level = 3
codegen-units = 1

[profile.release]
debug = true
