[package]
name = "arena-of-ideas"
version = "0.1.0"
edition = "2021"

[dependencies]
geng = { git = "https://github.com/kuviman/geng" }
serde = "1"
resvg = "0.22"
usvg = "0.22"
tiny-skia = "0.6"
regex = "1.5.6"
