[workspace]
members = [
    "macro-schema",
    "macro-server",
    "schema",
    "server",
    "ui",
    "utils",
    "utils-client",
]

[workspace.package]
version = "1.8.2"
edition = "2021"

[package]
name = "arena-of-ideas"
version.workspace = true
edition.workspace = true


[workspace.dependencies]
bevy = { version = "0.15.2", default-features = false, features = [
    "bevy_core_pipeline",
    "bevy_winit",
    "bevy_audio",
    "vorbis",
    "multi_threaded",
    "file_watcher",
    "bevy_ui",
    "default_font",
    "x11",
] }
spacetimedb = { version = "1.0.0" }
spacetimedb-sdk = "1.0.0"
spacetimedb-sats = "1.0.0"
spacetimedb-lib = "1.0.0"
strum = "0.26.2"
strum_macros = "0.26.2"
itertools = "0.12.1"
ron = "0.8.0"
serde = "1"
include_dir = "0.7.4"
thiserror = "2.0.3"
convert_case = "0.7.1"
bevy-trait-query = "0.7.0"
once_cell = "1.19.0"
bevy_egui = { version = "0.33.0", default-features = false, features = [
    "serde",
    "open_url",
    "render",
] }
ecolor = { version = "0.31.0", features = ["color-hex", "serde"] }
lerp = "0.5.0"
indexmap = { version = "2.6.0", features = ["serde"] }
colored = "2.0.0"
chrono = { version = "0.4.38", default-features = false, features = [
    "alloc",
    "std",
    "now",
] }
egui_extras = { version = "0.31.0", features = ["svg"] }
egui-notify = "0.19.0"
egui_tiles = "0.12.0"
humanize-duration = "0.0.6"
parking_lot = "0.12.3"
syn = "2.0.89"
darling = "0.20.10"
proc-macro2 = "1.0.92"
quote = "1.0.37"
tween = "2.0.1"
arboard = "3.4.1"
log = "0.4.19"
glam = { version = "0.29.2", features = ["serde"] }
rand = "0.8.5"
rand_chacha = "0.3.1"
color-hex = "0.2.0"
egui_colors = { version = "0.8.0", features = ["serde"] }
egui_double_slider = "0.7.0"
bimap = { version = "0.6.3", features = ["serde"] }
backtrace = "0.3.74"
mlua = { version = "0.10", features = ["lua54", "vendored"] }

[dependencies]
ui = { path = "ui" }
utils = { path = "utils" }
schema = { path = "schema" }
macro-schema = { path = "macro-schema" }
macro-client = { path = "macro-client" }
utils-client = { path = "utils-client" }

spacetimedb-sdk = { workspace = true }
spacetimedb-sats = { workspace = true }
spacetimedb-lib = { workspace = true }
bevy = { workspace = true }
bevy-trait-query = { workspace = true }
bevy_egui = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
itertools = { workspace = true }
ron = { workspace = true }
serde = { workspace = true }
include_dir = { workspace = true }
thiserror = { workspace = true }
convert_case = { workspace = true }
once_cell = { workspace = true }
ecolor = { workspace = true }
lerp = { workspace = true }
indexmap = { workspace = true }
colored = { workspace = true }
chrono = { workspace = true }
egui_extras = { workspace = true }
log = { workspace = true }
glam = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
parking_lot = { workspace = true }
tween = { workspace = true }
color-hex = { workspace = true }
egui_tiles = { workspace = true }
egui_colors = { workspace = true }
backtrace = { workspace = true }
mlua = {workspace = true }


bevy_asset_loader = { version = "0.22.0", features = [
    "standard_dynamic_assets",
] }
bevy_common_assets = { version = "0.12.0", features = ["ron"] }
serde_json = "1.0.104"
anyhow = "1.0.75"
clap = { version = "4.4.5", features = ["derive"] }
hex = "0.4.3"
home = "0.5.5"
noisy_bevy = "0.8.0"
egui_commonmark = "0.20.0"
bevy_tasks = "0.15.2"
regex = "1.10.5"
bevy_dylib = "0.15.2"
bevy-inspector-egui = "0.30.0"

[dependencies.winit]
version = "0.30.9"
features = ["default"]

[profile.dev.package."*"]
opt-level = 3
codegen-units = 1

[profile.release]
debug = true
