[package]
name = "bevy-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
bevy_asset_loader = { version = "0.17.0", features = [
    "standard_dynamic_assets",
] }
bevy_common_assets = { version = "0.7.0", features = ["ron"] }
bevy = "0.11.0"
bevy-inspector-egui = "0.19.0"
bevy_egui = "0.21"
log = "0.4.19"
serde = "1"
serde_json = "1.0.104"
ron = "0.8.0"
itertools = "0.11.0"
anyhow = "1.0.75"
strum_macros = "0.25.2"
tween = "2.0.1"
