[workspace]
members = [
    "macro-schema",
    "macro-server",
    "nodes-server",
    "schema",
    "server",
    "ui",
    "utils",
    "utils-client",
]

[workspace.package]
version = "1.8.2"
edition = "2021"

[package]
name = "arena-of-ideas"
version.workspace = true
edition.workspace = true


[workspace.dependencies]
bevy = { version = "0.14.1", default-features = false, features = [
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_winit",
    "bevy_audio",
    "vorbis",
    "multi_threaded",
    "file_watcher",
    "bevy_ui",
    "bevy_text",
    "default_font",
    "x11",
] }
spacetimedb = { version = "=1.0.0-rc1" }
strum = "0.26.2"
strum_macros = "0.26.2"
itertools = "0.12.1"
ron = "0.8.0"
serde = "1"
include_dir = "0.7.4"
thiserror = "2.0.3"
convert_case = "0.6.0"
bevy-trait-query = "0.6.0"
once_cell = "1.19.0"
bevy_egui = { version = "0.29.0", default-features = false, features = [
    "serde",
    "open_url",
    "render",
] }
ecolor = { version = "0.28.1", features = ["color-hex"] }
lerp = "0.5.0"
indexmap = { version = "2.6.0", features = ["serde"] }
colored = "2.0.0"
chrono = { version = "0.4.38", default-features = false, features = [
    "alloc",
    "std",
    "now",
] }
egui_extras = { version = "0.28.1", features = ["svg"] }
humanize-duration = "0.0.6"
parking_lot = "0.12.3"
syn = "2.0.89"
darling = "0.20.10"
proc-macro2 = "1.0.92"
quote = "1.0.37"
tween = "2.0.1"
arboard = "3.4.1"

[dependencies]
ui = { path = "ui" }
utils = { path = "utils" }
schema = { path = "schema" }
utils-client = { path = "utils-client" }
nodes-client = { path = "nodes-client" }

bevy = { workspace = true }
bevy-trait-query = { workspace = true }
bevy_egui = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
itertools = { workspace = true }
ron = { workspace = true }
serde = { workspace = true }
include_dir = { workspace = true }
thiserror = { workspace = true }
convert_case = { workspace = true }
once_cell = { workspace = true }
ecolor = { workspace = true }
lerp = { workspace = true }
indexmap = { workspace = true }
colored = { workspace = true }
chrono = { workspace = true }
egui_extras = { workspace = true }

spacetimedb-sdk = "=1.0.0-rc1"
spacetimedb-sats = "=1.0.0-rc1"
spacetimedb-lib = "=1.0.0-rc1"

bevy_asset_loader = { version = "0.21.0", features = [
    "standard_dynamic_assets",
] }
bevy_common_assets = { version = "0.11.0", features = ["ron"] }
log = "0.4.19"
serde_json = "1.0.104"
anyhow = "1.0.75"
rand = "0.8.5"
rand_chacha = "0.3.1"
clap = { version = "4.4.5", features = ["derive"] }
hex = "0.4.3"
home = "0.5.5"
lazy_static = "1.4.0"
noisy_bevy = "0.7.0"
egui_commonmark = "0.17.0"
bevy_tasks = "0.14.1"
regex = "1.10.5"
bevy_dylib = "0.14.1"
bevy-panic-handler = "3.0.0"
bevy-inspector-egui = "0.25.0"

[dependencies.winit]
version = "0.30.5"
features = ["default"]

[profile.dev.package."*"]
opt-level = 3
codegen-units = 1

[profile.release]
debug = true
