[package]
name = "arena-of-ideas"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
bevy = { version = "0.11.0", default-features = false, features = [
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_winit",
    "multi-threaded",
    "filesystem_watcher",
] }
ecolor = { version = "0.22.0", features = ["color-hex"] }
bevy_asset_loader = { version = "0.17.0", features = [
    "standard_dynamic_assets",
] }
bevy_common_assets = { version = "0.7.0", features = ["ron"] }
bevy-inspector-egui = "0.19.0"
bevy_egui = "0.21"
bevy_mod_picking = "0.15.0"
log = "0.4.19"
serde = "1"
serde_json = "1.0.104"
ron = "0.8.0"
itertools = "0.11.0"
anyhow = "1.0.75"
strum_macros = "0.25.2"
tween = "2.0.1"
rand = "0.8.5"
color-hex = "0.2.0"
rand_chacha = "0.3.1"
colored = "2.0.0"
bevy_pkv = "0.8.0"
clap = { version = "4.4.5", features = ["derive"] }
spacetimedb-sdk = "0.7.2"
bevy_kira_audio = { version = "0.17.0", features = ["settings_loader"] }

[profile.dev.package."*"]
opt-level = 3
