[package]
name = "arena-of-ideas"
version = "0.1.0"
edition = "2021"

[dependencies]
geng = "0.14.0"
serde = "1"
resvg = "0.22"
usvg = "0.22"
tiny-skia = "0.6"
notify = "4.0.17" # File watch
regex = "1.5.6"
chrono = "0.4"
tween = "1.0.0"
strfmt = "0.2.2"
enum-utils = "0.1.2"

[patch.crates-io]
# Temp workaround until update in geng, as this issue is already fixed upstream
# https://github.com/jdm/tinyfiledialogs-rs/issues/36
tinyfiledialogs = { git = "https://github.com/kuviman/tinyfiledialogs-rs", branch = "fix-cross" }
geng = { git = "https://github.com/kuviman/geng", branch = "main" }
