[package]
name = "arena-of-ideas"
version = "0.1.0"
edition = "2021"

[dependencies]
geng = "0.12"
serde = "1"
resvg = "0.22"
usvg = "0.22"
tiny-skia = "0.6"
notify = "4.0.17" # File watch
regex = "1.5.6"
chrono = "0.4"
