[package]
name = "extra"
version.workspace = true
edition.workspace = true

[dependencies]
extra-macros = { path = "../extra-macros" }
bevy = { workspace = true }
ron = { workspace = true }
serde = { workspace = true }
