[package]
name = "spacetime-module"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
spacetimedb = { workspace = true }
log = "0.4"
itertools = "0.12.0"
anyhow = "1.0.75"
pwhash = "1.0.0"
hex = "0.4.3"
rand = "0.8.5"
