[package]
name = "spacetime-module"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
schema = { path = "../schema" }
macro-schema = { path = "../macro-schema" }
macro-server = { path = "../macro-server" }
utils = { path = "../utils", features = ["server"] }
spacetimedb = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
chrono = { workspace = true }
glam = { workspace = true }
ron = { workspace = true }
serde = { workspace = true }
log = "0.4"
itertools = "0.12.0"
hex = "0.4.3"
rand = { version = "0.8.5", default-features = false }
rand_seeder = "0.2.3"
rand_pcg = "0.3.1"
bcrypt-no-getrandom = "0.16.0"
hashbrown = { workspace = true }
