[package]
name = "spacetime-module"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
spacetimedb = { version = "0.8.0", features = ["getrandom"] }
log = "0.4"
itertools = "0.12.0"
anyhow = "1.0.75"
pwhash = "1.0.0"
hex = "0.4.3"
