[package]
name = "utils-client"
version.workspace = true
edition.workspace = true

[dependencies]
schema = { path = "../schema" }
once_cell = { workspace = true }
bevy = { workspace = true }
bevy_egui = { workspace = true }
parking_lot = { workspace = true }
