name: GitHub Readme YouTube Cards
on:
  schedule:
    # Runs every hour, on the hour
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Allow the job to commit to the repository
    permissions:
      contents: write
    # Run the GitHub Readme YouTube Cards action
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCBPNPR5nWAQL48PvycsTw4Q
          max_videos: 3
          max_title_lines: 2
          playlist_id: PLqgg20d6CY1Nu0NvohkFQR-9C2RebyEuV